Made objj point to Frameworks in lib.
Reviewed by tom.

diff --git a/Tools/objj/objj b/Tools/objj/objj
--- a/Tools/objj/objj
+++ b/Tools/objj/objj
@@ -43,9 +43,9 @@ case "$UNAME" in
         ;;
 esac
 
-if [ -e $STEAM_BUILD/Objective-J.build/Release/Rhino ]; then
+#if [ -e $STEAM_BUILD/Objective-J.build/Release/Rhino ]; then
     $RLWRAP java -classpath $CLASSPATH objj $OBJJ_LIB $STEAM_BUILD $@
     #$RLWRAP java -classpath $CLASSPATH org.mozilla.javascript.tools.shell.Main $OBJJ $OBJJ_LIB $STEAM_BUILD $@
-else
-    echo "Missing frameworks at $STEAM_BUILD/Objective-J.build/Release/Rhino" 1>&2
-fi
+#else
+#    echo "Missing frameworks at $STEAM_BUILD/Objective-J.build/Release/Rhino" 1>&2
+#fi
